### ISSUE TITLE
Atualizar versão Java 1.6 para 1.8

### ISSUE THREAD

**Issue by andersonscherrrer** [wpivotto/vraptor-jasperreport#17]
Estou obtendo o seguinte erro ao gerar o relatório:
java.util.ArrayList; local class incompatible:
Provavelmente porque o plugin está usando ArrayList do java 1.6 e eu estou usando o Java 1.8 
É possível atualizar a versão do java? Se for, eu posso tentar.

**Comment by wpivotto** [comment]
Olá Anderson, você tem como postar o stacktrace completo? 
Obrigado

**Comment by andersonscherrrer** [comment]
Eu baixei o projeto, e alterei pra java8 e a versão do vraptor, e continua o erro:

GRAVE: Servlet.service() for servlet [default] in context with path [/storemanager] threw exception
java.lang.RuntimeException: net.sf.jasperreports.engine.JRException: Error loading object from file : C\workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\rsys-storemanager\WEB-INF\reports\report.jasper
	at br.com.caelum.vraptor.jasperreports.exporter.DefaultExporter.to(DefaultExporter.java:65)
	at br.com.caelum.vraptor.jasperreports.exporter.DefaultExporter$Proxy$_$$_WeldClientProxy.to(Unknown Source)
	at br.com.caelum.vraptor.jasperreports.download.ReportDownload.getContent(ReportDownload.java:52)
	at br.com.caelum.vraptor.jasperreports.download.ReportDownload.write(ReportDownload.java:46)
	at br.com.caelum.vraptor.observer.download.DownloadView.of(DownloadView.java:50)
	at br.com.caelum.vraptor.observer.download.DownloadObserver.download(DownloadObserver.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
	at org.jboss.weld.injection.MethodInvocationStrategy$DefaultMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:109)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:306)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:284)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:262)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:271)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:260)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:89)
	at br.com.caelum.vraptor.observer.ExecuteMethod$1.call(ExecuteMethod.java:87)
	at br.com.caelum.vraptor.observer.ExecuteMethod$1.call(ExecuteMethod.java:72)
	at br.com.caelum.vraptor.core.Try.run(Try.java:18)
	at br.com.caelum.vraptor.observer.ExecuteMethod.execute(ExecuteMethod.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:306)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:284)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:262)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:271)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:260)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:89)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:78)
	at br.com.rsyssoftwares.coreweb.view.GlobalInterceptor.intercept(GlobalInterceptor.java:34)
	at br.com.rsyssoftwares.coreweb.view.GlobalInterceptor$Proxy$_$$_WeldClientProxy.intercept(Unknown Source)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler$1.call(ToInstantiateInterceptorHandler.java:71)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler$1.call(ToInstantiateInterceptorHandler.java:68)
	at br.com.caelum.vraptor.core.Try.run(Try.java:18)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.executeSafely(ToInstantiateInterceptorHandler.java:68)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
	at br.com.caelum.brutauth.interceptors.BrutauthMapInterceptor.intercept(BrutauthMapInterceptor.java:36)
	at br.com.caelum.brutauth.interceptors.BrutauthMapInterceptor$Proxy$_$$_WeldClientProxy.intercept(Unknown Source)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler$1.call(ToInstantiateInterceptorHandler.java:71)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler$1.call(ToInstantiateInterceptorHandler.java:68)
	at br.com.caelum.vraptor.core.Try.run(Try.java:18)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.executeSafely(ToInstantiateInterceptorHandler.java:68)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
	at br.com.caelum.brutauth.interceptors.BrutauthRuleInterceptor.intercept(BrutauthRuleInterceptor.java:39)
	at br.com.caelum.brutauth.interceptors.BrutauthRuleInterceptor$Proxy$_$$_WeldClientProxy.intercept(Unknown Source)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler$1.call(ToInstantiateInterceptorHandler.java:71)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler$1.call(ToInstantiateInterceptorHandler.java:68)
	at br.com.caelum.vraptor.core.Try.run(Try.java:18)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.executeSafely(ToInstantiateInterceptorHandler.java:68)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
	at br.com.caelum.vraptor.interceptor.ExceptionHandlerInterceptor.intercept(ExceptionHandlerInterceptor.java:75)
	at br.com.caelum.vraptor.interceptor.ExceptionHandlerInterceptor$Proxy$_$$_WeldClientProxy.intercept(Unknown Source)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler$1.call(ToInstantiateInterceptorHandler.java:71)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler$1.call(ToInstantiateInterceptorHandler.java:68)
	at br.com.caelum.vraptor.core.Try.run(Try.java:18)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.executeSafely(ToInstantiateInterceptorHandler.java:68)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
	at br.com.caelum.vraptor.interceptor.FlashInterceptor.intercept(FlashInterceptor.java:98)
	at br.com.caelum.vraptor.interceptor.FlashInterceptor$Proxy$_$$_WeldClientProxy.intercept(Unknown Source)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler$1.call(ToInstantiateInterceptorHandler.java:71)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler$1.call(ToInstantiateInterceptorHandler.java:68)
	at br.com.caelum.vraptor.core.Try.run(Try.java:18)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.executeSafely(ToInstantiateInterceptorHandler.java:68)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:61)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.start(DefaultInterceptorStack.java:93)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack$Proxy$_$$_WeldClientProxy.start(Unknown Source)
	at br.com.caelum.vraptor.observer.RequestHandlerObserver.handle(RequestHandlerObserver.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:306)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:284)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:262)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:271)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:260)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:89)
	at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at br.com.rsyssoftwares.coreweb.filters.ParametersFilter.doFilter(ParametersFilter.java:34)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: net.sf.jasperreports.engine.JRException: Error loading object from file : C:\sysnenos\workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\rsys-storemanager\WEB-INF\reports\report.jasper
	at net.sf.jasperreports.engine.util.JRLoader.loadObject(JRLoader.java:131)
	at net.sf.jasperreports.engine.util.JRLoader.loadObject(JRLoader.java:103)
	at net.sf.jasperreports.engine.util.JRLoader.loadObjectFromFile(JRLoader.java:94)
	at br.com.caelum.vraptor.jasperreports.ReportLoader.loadFromDisk(ReportLoader.java:42)
	at br.com.caelum.vraptor.jasperreports.ReportLoader.load(ReportLoader.java:22)
	at br.com.caelum.vraptor.jasperreports.ReportLoader$Proxy$_$$_WeldClientProxy.load(Unknown Source)
	at br.com.caelum.vraptor.jasperreports.exporter.DefaultExporter.fill(DefaultExporter.java:79)
	at br.com.caelum.vraptor.jasperreports.exporter.DefaultExporter.fillAll(DefaultExporter.java:72)
	at br.com.caelum.vraptor.jasperreports.exporter.DefaultExporter.to(DefaultExporter.java:62)
	... 114 more
Caused by: java.io.InvalidClassException: java.util.ArrayList; local class incompatible: stream classdesc serialVersionUID = 8664875232659988799, local class serialVersionUID = 8683452581122892189
	at java.io.ObjectStreamClass.initNonProxy(Unknown Source)
	at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
	at java.io.ObjectInputStream.readClassDesc(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
	at java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
	at java.io.ObjectInputStream.defaultReadObject(Unknown Source)
	at net.sf.jasperreports.engine.base.JRBaseReport.readObject(JRBaseReport.java:825)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at java.io.ObjectStreamClass.invokeReadObject(Unknown Source)
	at java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.readObject(Unknown Source)
	at net.sf.jasperreports.engine.util.JRLoader.loadObject(JRLoader.java:127)
	... 122 more

**Comment by wpivotto** [comment]
Parece um problema de serialização. Você tem certeza que seu arquivo jasper foi compilado com a mesma versão da declarada no pom.xml?

**Comment by andersonscherrrer** [comment]
Seguinte, eu coloquei em outro projeto com java 8 e funcionou, mas no projeto que estou tentando tem vraptor-brutauth e alguns interceptors e tem bem mais dependencias no pom.xml. Vou ter que descobrir o que ta conflitando. 
Mas o erro é meu mesmo, pelo visto kkk.

**Comment by wpivotto** [comment]
Tenta retornar o arquivo jrxml no método getTemplate que a lib vai compilar com a versão declarada no pom. Talvez ajude ao menos no debug.

**Comment by andersonscherrrer** [comment]
Funcionou! Só não entendi porque o .jasper em uma aplicação funcionou e na outra não. Mas vou tentar gerar o relatório de novo. 
Valew pela força.

**Comment by andersonscherrrer** [comment]
Descobri o que era. 
No build desse projeto, eu faço um filtro nas jsp pra incluir algumas coisas(Versão por exemplo), e ele estava zoando o arquivo .jasper, fui lá e adicionei uma exclusão e funcionou.

Meee a tarde inteira pra desobrir que era isso kkkk 

Desculpa encomodar, e gerar essa issue.
